### PR TITLE
The app is now resizeable

### PR DESCRIPTION
**Pull request by mayuso**
Minimum size now 1280x768. (Lower than that works fine in every window except for the actual gameplay window, so I decided to set those minimum values until I find a solution). Default size is 1280x900 (Resizeable). I didn't really think about this too much, 1280x900 felt good, we can easily change it if necessary.

I might have left some windows without proper scalability, just tell me if you find any.

Please, test and tell me if you find any other problem/bug, and I hope you like these changes :)

### CODE REVIEW

**Comment by mayuso** [comment]
I forgot to mention this fixes #84

**Comment by webadict** [comment]
Worst case scenario, I can always close it. Demilich seems like he's been
busy lately.

**Comment by mayuso** [comment]
Close the PR? Why? Breaks the code?

**Comment by webadict** [comment]
No no, I meant the Issue. I haven't even tested this change yet.

**Comment by mayuso** [comment]
No, leave it until the PR is tested and merged please. It works for me, but still would like more people to test it. This is the first PR I make that actually has any code, so I prefer to be sure I did not f*ck up.

**Comment by demilich1** [comment]
I just tested the changes, nothing seems to be broken. However, the benefits are very marginal in my opinion. The new minimum width is actually larger than the previous width (1266 vs 1036) and the new minimum height is 44 pixels smaller than the previous height (761 vs 805). These are the values on Windows 10, it may vary slightly due to different operating systems having different window borders.
The UI itself does not resize at all, it is just the window (i.e. the border) that changes. The height gain is basically "cheated" in the sense that it just cuts things off. You can see that clearly when entering sandbox mode and scaling the window to the minimum size. The hand cards of you and your opponent are partially cut off. Also when maximizing the window you basically get a big empty window with some UI in the center. 

I would really like that somebody else tries this out before merging. If it is a small improvement, I will still merge it in; if not, we may have to think about some other UI changes.

**Comment by mayuso** [comment]
I have a 1366x768 laptop, the last versions had the correct window size, but the elements did not scale (Some of them were out of bounds and did not appear (Usually happened with the buttons in the lower part, Back/Start and donation buttons specially)). This is fixed in this PR if I am not mistaken.

About the minimum values, I will check those asap, I did not realise I actually set higher values than the size we had before.

**Comment by mayuso** [comment]
I saw that some contributors want a public release soon, feel free to ignore this PR for now, it might take me a decent time to find the sweet spot where everything feels good on the GUI. 

We can leave it for the next release (In case we see it is useful after I fix the issues).

**Comment by mayuso** [comment]
You know what? You are right, it's useless haha. Let's ignore it.

**Comment by webadict** [comment]
Doesn't it make the actual sandbox mode viewable with 6 minions trying to
play a 7th in the leftmost spot, which the program currently can't do due
to width limits?

**Pull request closed without merging**
