### PR TITLE
Minor Fix 1 for 1.0.2

### LINKED ISSUE #88: [Bug] Freezing Trap and Explosive Trap won't trigger
Using version 1.0.1 and Freezing Trap will not trigger when attacking a minion or a hero. Explosive Trap also won't trigger.

### LINKED ISSUE #90: [Murloc Knight] - summoning order
Bug report received via email:

Murloc Knight is summoning it's Inspire minion to the right of the summoned Silver Hand Recruit. It should be adjacent to the Murloc Knight. This may be an issue with the order of the summons.

### LINKED ISSUE #91: [Knife Juggler] - overkilling with trigger
Bug report received via email:

In certain cases Knife Juggler is still hitting dead minions when triggered by Haunted Creeper's Deathrattle. For example, if a 1/2 Haunted Creeper attacks into a 2/1 minion, Metastone will correctly ignore the 2/1 minion and send each dagger somewhere else. However, if a 1/2 Haunted Creeper attacks into a 2/2 minion, both daggers will sometimes hit that minion, overkilling it by 1. This also happens with Knife Juggler + Implosion.

Most probably this is not an issue specific to Knife Juggler, but affects all deal-damage-when-something-happens triggers.

### PR DESCRIPTION
**Pull request by webadict**
Issues:
-Fixes #88. Source player is now checked correctly for all triggers. Triggers without an Event Source will simply ignore the case, but this should help bring together each Event and Trigger.
-Fixes #90. Missing summon position tag.
-Fixes #91. Changes Knife Juggler to use Missiles.

Improvements:
-Added Weapon mana cost modifiers. This allows weapons to modify both their own cost and the cost of other cards.
-Added active and inactive player owned conditions replacing onOwnTurnOnly.
-Added versatility to Discover mechanic to allow Discoveries outside of one's own class, including opponent's class.
-Fixed improper silencing mechanics. Silence should increase HP if it increases maxHP. That was incorrect thinking from a long time ago.
-Fixed Discover bug when Discovering with no choices.

### CODE REVIEW

**Comment by mayuso** [comment]
Just small reminder: I think this should be named Small fix for 1.0.2. :P (1.0.1 was released 3 days ago) :P

**Comment by webadict** [comment]
All fixed now :P

**Comment by demilich1** [comment]
hasArg and getArg are totally fine, as they don't modify the underlying HashMap ;)

**Comment by demilich1** [comment]
By the way, thanks for fixing my shit ;) I just tested your changes, unfortunately two of the unit tests are failing now.

Eydis Darkbane once again triggers when the opponent casts a spell on her. And Lord Jaraxxus is longer affected by Repentance (which probably is because Repentance is no longer triggering at all). What is interesting: I had those exact two tests failing when I refactored the code and centralized .determineTargetPlayer.

I think this may be a deeper problem, probably because the meaning of 'targetPlayer' is interpreted differently for different cards. When I introduced this variable, I basically used it to limit triggers to certain player. So 'targetPlayer: SELF' meant 'This trigger only works for me, not for my opponent'. Later on, you re-interpreted 'targetPlayer' as 'the player who gets targeted by an effect' which is a totally different meaning. To be fair, the name 'targetPlayer' was a rather unfortunate choice and your interpretation makes more sense. But now I think we have a mix between those two meanings :(

**Comment by webadict** [comment]
That makes sense. I rewrote the targeting stuff mostly for myself, since it made more sense for this to target and have a source (since I tried to decrease the number of triggers, which kinda increased other things...) It does have an unfortunate name, and it could probably be changed to something like PlayerTargeting or something less confusing.

I can try to take a look at the target players and look at the naming later. Right now, I'm going to modify MetaSpell so that it uses the SpellArg Spells instead, which feels like it's much better overall.

I have ideas for Jaraxxus as well, since it still isn't fully correct, but it involves changing how the Secrets can target, and then redirecting all the secrets that target on minion summoning to target the newly spawned hero instead. This should be the correct method, as there shouldn't really be a minion spawned event that triggers Knife Juggler, since the Jaraxxus minion never actually finishes summoning.

**Comment by demilich1** [comment]
Big thumbs up for MetaSpell using 'spells' now, this was actually on my imaginary TODO list for a long time. Much nicer this way.

Would you like me to already merge the pull request now and fix the bugs in the next one or should I wait a little bit longer?

**Comment by webadict** [comment]
Wait a bit longer. I think I can fix those two secrets real quick.

**Comment by webadict** [comment]
... Sometimes, I'm dumb.

**Comment by webadict** [comment]
Honestly, there's no way to fix Blessings of Wisdom the way it is now. The problem is that the trigger switches sides when mind controlled, so that it does not accurately draw cards for the original player. No idea how to fix that.

**Comment by demilich1** [comment]
I have an idea to solve the Blessings of WIsdom issue. Do you consider the PR ready to be merged otherwise?

**Comment by webadict** [comment]
Yeah, I beleive so. I can't think of fix for Jaraxxus yet, so I say if it's
working, do it.

**Comment by demilich1** [comment]
Jaraxxus is working fine - in fact, all unit tests are passing. I will merge this, write a new unit test for Blessing of Wisdom and then fix it.

**Comment by mayuso** [comment]
Hey @demilich1, can you give @webadict permissions on the repo so that he can actually close fixed issues? I usually come and read all issues in case I find something I can help with, and it is a bit annoying to see the same "already fixed" issues every day :)

**Pull request merged**
