### PR TITLE
Minor Bug Fix 4 for 1.0.0

### PR DESCRIPTION
**Pull request by webadict**
-Fixed Dark Wispers being listed as a Classic card.
-Added Aura Tests.
-Added Blackrock Mountain Tests.
-Fixed Hero Power usage number bugs.
-Fixed various Card Cost Modifier bugs, and added new functionality.
-Fixed various Trigger bugs.
-Fixed Faceless copying Auras.
-Removed AddCardCostModifierSpell and added new functionality to CardCostModifierSpell.

EDIT: A thorough investigation has been made, and no critical bugs have been found.

### CODE REVIEW

**Comment by webadict** [comment]
I did some minor testing. I'll do some more testing eventually, but I squashed some Brann weapon bugs.

**Comment by webadict** [comment]
Testing completed. It appears the game does not have any critical flaws that are readily apparent.

**Comment by demilich1** [comment]
I just tested your branch, for me most of the new Blackrock Mountain unit tests are failing. Do they complete for you?

**Comment by webadict** [comment]
Oh, I never got the tests to go. I don't see why they would fail, but I say
just remove it for now. I can look at them some other time.

**Pull request merged**
