### PR TITLE
Minor Fixes v1.3

### PR DESCRIPTION
**Pull request by webadict**
Bug Fixes:
-Weapons no longer break at 0 Attack. If a Weapon's Attack is below 0, 0 is still given for the Attack value.
-Changed Ragnaros' Class to Boss.
-Fixed Mal'Ganis not granting Immune status when no other minion were on the board.
-Fixed Frozen minions incorrectly checking Freeze status at the end of the turn. <-- Probs should put at least this into 0.9.8, since it's a rather unpleasant bug.
-Shadowform no longer resets your Hero Power if you already have Mind Shatter.

Additions:
-Nefarian and Burgle now steal the correct cards from Ragnaros (2x Tail Swipe and 2x The Coin, respectively) This interaction also works against Adventure Bosses... You know, just in case.
-Added Tail Swipe
-EDIT: Added Card Counter

### CODE REVIEW

**Comment by demilich1** [comment]
Thanks for the 'freezing' fix. I agree that this is pretty important and updated the binaries with this fix (the other stuff is not yet in)

**Comment by webadict** [comment]
Gorehowl never actually breaks if you use it exclusively on minions. This is the intended interaction. If Gorehowl reaches 0 Attack (or less!) it simply adds no Attack to your Hero. If your Hero has 0 Attack, then your Hero is unable to attack, which is exactly how it currently functions, even without destroying the weapon.

As confirmation, from the wiki (http://hearthstone.gamepedia.com/Gorehowl):
"Through repeated use, Gorehowl's Attack can be reduced to 0 or even lower (see below). Once it reaches 0 it will not be possible to attack using the Gorehowl, but the weapon will not destroy itself.[1]"
"It is possible to get a -1 or lower Attack Gorehowl if you use effects like Heroic Strike or Spiteful Smith to continue to attack with the Gorehowl after it hits 0 Attack.[2]
Negative Attack is displayed as a 0. If you don't have another source of Attack, you cannot swing the weapon at all.
If Spiteful Smith is buffing your Negative Attack Gorehowl, it buffs the negative value, not 0. For example, a -1 Attack Gorehowl gains 2 Attack from Spiteful Smith and becomes 1 Attack."

The only way to destroy Gorehowl at 0 Attack is to either get a positive Attack value and attack face or to equip a new weapon.

**Comment by demilich1** [comment]
Oh okay, didn't know that. By the way, I really appreciate your elaborate reasoning and citing of sources when you change rules in the code. Thanks for that!

**Comment by webadict** [comment]
No problem. Like I said, I'm trying to be as thorough as possible. If there's ever a question of why, I make sure there's a reason for the change, and I recheck my sources as well.

I should note that Ragnaros, as I have implemented here, is TECHNICALLY incorrect. He should work as it currently is, but he currently works as I'm suggesting in this fix. If the dev team ever decide to fix it (or directly say that it's a bug, instead of indirectly), then he should generate cards from the base class. However, the fix to ReceiveRandomCard should still be there, as a fallback case for cards.

**Comment by webadict** [comment]
The condition is needed for a very good reason, actually.

The PutRandomMinionOnBoard pulls a random minion from your Deck or Hand and tries to place it on the board and then removes it from the deck. So, in essence, it destroys the card if your Board is full, which absolutely no card should ever do. However, there is probably a better way to set this up, where turning the summon() method into a boolean return can tell us if the minion was summoned successfully and then remove it from there.

**Comment by demilich1** [comment]
You are right, I implemented it as suggested

**Pull request merged**
