### PR TITLE
Project structure refactor

### PR DESCRIPTION
**Pull request by akoscz**
Separating `game` and `ui` source code and data files into their respective modules.

- added app, game, shared and cards modules
- shuffled source and data files around into their respective modules
- implemented loading data files from jar resource file produced by the cards module
- added ability to load cards and decks from `~/metastone/cards` and `~/metastone/decks`
- updated README.md with project structure changes and expanded on Windows and Linux/OSX gradle command examples

### CODE REVIEW

**Comment by akoscz** [comment]
Before this gets approved for merge,  I would like to get some folks to run it and tell me if I missed anything.  For instance, I'm not sure what to do with the training data directory that's hanging out at the root of the project.

**Comment by kairos4242** [comment]
I'll try to set up Gradle and run it, but no guarantees on how long that'll take. It might be easier for demilich1 or webadict to take a look instead.

**Comment by akoscz** [comment]
@kairos4242 there's no setup necessary for Gradle.   We have the gradle-wrapper bundled with the project.  When your run the `gradlew` (Linux/OSX) or `gradlew.bat` (Windows) command, it will invoke gradle-wrapper.jar and download the appropriate dependencies for gradle.  All of it is automated for you making the gradle installation super easy.

**Comment by kairos4242** [comment]
@akoscz Oh, okay, I'll try that out right now then.

**Comment by kairos4242** [comment]
Hmm, I'm getting an error message but the window closes before I can read it. This may take a bit more work than expected.

**Comment by akoscz** [comment]
@kairos4242 sorry i should have been a bit more clear on how to build and the app using gradle.  `gradlew` is a command line utility.  In other words, you need to open up a terminal (Linux/OSX) or a command prompt (Windows), navigate to the folder where you have checked out the branch and then run `./gradlew run` (Linux/OSX) or `gradlew.bat run` (Windows).    I have documented these steps and some more stuff in the README.mb file.  https://github.com/akoscz/metastone/blob/modules2/README.md

**Comment by demilich1** [comment]
I just tested this, getting the following error when using 'gradlew run':

Exception in Application start method13:40:35 ERROR - \cards directory not found in resources

I did run a 'gradlew compileJava' before (and it ran successfully).

Also I cannot seem to get the project working in my IDE (Eclipse), even your updated README did not help me. Do I need to import the modules as separate projects?

**Comment by akoscz** [comment]
@demilich1  Thanks for taking a look and for the  feedback.
Regarding Eclipse,  it's been awhile since I've used Eclipse on a daily basis, so I'll need to review the steps for Eclipse and update the documentation.

As for the cards dir error,  are you on Windows?  I bet it's a OS path delimiter error.   I'll need to spin up a Windows VM and try this out.

**Comment by demilich1** [comment]
Yes, I am on Windows

**Comment by akoscz** [comment]
Indeed it is a file separator issue.  I made the mistake of thinking that the CLASSPATH will use the OS's file separator character. [`CardCatalogue.CARDS_FOLDER = File.separator + "cards";`](https://github.com/akoscz/metastone/blob/modules2/game/src/main/java/net/demilich/metastone/game/cards/CardCatalogue.java
)

The exception is being thrown in [`ResourceLoader.loadJsonInputStreams(String rootDir, boolean fromFileSystem)`](https://github.com/akoscz/metastone/blob/modules2/shared/src/main/java/net/demilich/metastone/utils/ResourceLoader.java)

I'll make the appropriate changes later tonight and update the PR.

**Comment by akoscz** [comment]
I pushed a quick fix.  I haven't tested it on Windows yet, i'll do that tonight.  If you have a couple of minutes give it another go :)  Thanks!

**Comment by kairos4242** [comment]
@akoscz Oh, okay, I was trying to run it through git powershell. I'll try it again ASAP.

**Comment by akoscz** [comment]
@demilich1 Filepath issues are really fixed now.  I have verified the fix on a Windows machine.  The README.md has also been updated with more accurate instructutions on how to import the multi-module project into Eclipse.  Unfortunately Eclipse does not play nicely with multi-module gradle projects so there's a ugly hack necessary to turn off Cyclical Dependencies on the Build Path.  See https://issues.gradle.org/browse/GRADLE-2200

**Comment by demilich1** [comment]
Okay, it works now for me. Would you mind incorporating the latest changes from master so I can merge without conflicts?

**Comment by akoscz** [comment]
Take a look at my comments on https://github.com/demilich1/metastone/pull/130
I attempted to merge `master` into my branch and ran into problems, so I pulled down a fresh copy of `master` and sure enough the same failures are present.  I'll hold off on merging and resolving conflicts until `master` is stable.

**Comment by akoscz** [comment]
@demilich1 Can you give me some pointers on what to do with the [`training`](https://github.com/akoscz/metastone/tree/modules2/training) directory and its contents.  Is the intention to distribute these files with the app?  I couldn't find a way to invoke a training mode from within the app ui to read or write these json files in the `training` dir.  If the files in the `training` dir are not meant to be distributed with the app, then I would like to propose to change the reading and writing of training data to live in the user's home metastone training dir: `~/metastone/training`.

**Comment by demilich1** [comment]
The /training directory is not used at all at the moment. In the future I want to use it for deck-specific AI data. There is a hidden prototype in the app, which you may access by setting DEV_BUILD = true in AppConfig.java. Doing so will add a new item in the Main Menu called 'Training' which can be used to train the AI. Please note that this is not a supported feature, it may even not work at all (last time I tried was quite some time ago).

The intention in the future would be to store optimized training data for the pre-built decks which come with MetaStone. So it would probably belong to the 'cards' module?

**Comment by akoscz** [comment]
Got it.  thanks,  that's what I needed to know.  I will make the appropriate code changes to read training data from cards.jar file that the `cards` module produces.  Is it conceivable that user's will also provide their own training data?  In other words, do we want to also read training data from `~/metastone/training` in addition to reading training data from the `cards` module?

**Comment by demilich1** [comment]
Yes, for the feature to be really useful the users need some way to save their own training data. However (and this also applies to custom cards) the current solution is not really how most other programs handle this scenario. Usually there is a user data folder (<username>/Documents/ on Windows and /home on Linux) where user created data is stored. I would like to switch to that approach in the near future.

**Comment by akoscz** [comment]
@demilich1  go ahead and pull in https://github.com/demilich1/metastone/pull/131 first and I'll merge again.

**Comment by demilich1** [comment]
@akoscz Thank you

**Comment by akoscz** [comment]
@demilich1 Feel free to merge whenever you're ready.   I've got a few more changes coming in separate PR's from https://github.com/akoscz/metastone/tree/training and https://github.com/akoscz/metastone/tree/buildConfig

**Pull request merged**
