### PR TITLE
Minor Bug Fixes 2 for 0.9.9

### PR DESCRIPTION
**Pull request by webadict**
-Fixed Imp Gang Boss and Ram Wrangler to summon minions to the correct positions.
-Fixed Secrets to differentiate between played from the Hand or by effect.
-Added a Set Aside Zone for players to put cards in. This is vastly important.
--The Set Aside Zone is incredibly important for cards that are removed from the game in a way other than destruction. For now, this really only includes transformation. The minions are still technically able to be targeted from other zones, so something like Brann Bronzebeard + Recombobulator still activates twice on the original minion that has been targeted, because it still exists. Mostly, this removes a bunch of errors within the game about minions that aren't dead, but aren't in the game.
-Fixed Transformations to do a whole heck of a lot. Let's just break this one up:
--Minions should no longer enter the Graveyard after transformation.
--Secrets now interact with the transformed minion.
--Minions should no longer activate 'on Summon' effects after transformation.
--Minions should no longer have issues with Brann Bronzebeard while transforming with a Battlecry.
-Fixed Brann Bronzebeard interacting with Choose One
-Fixed Sir Finley Mrrgglton giving Hero Powers you have.

### CODE REVIEW

**Comment by demilich1** [comment]
Thanks again for your fixes webadict.

I just tested those changes and unfortunately this version does not pass the 100k random play tests. I was not able to locate the bug with a quick look, it might be related to the new transform minion code.

Also the Mal'Ganis fix cannot stay like this, because if you play Jaraxxus -> Mal'ganis, your hero is actually considered a demon (killable by Sacrifical Pact) and thus benefits from the attack bonus part of the aura.

**Comment by webadict** [comment]
Weirdly enough, it doesn't actually benefit hero Jaraxxus! This is due to
the difference between Hero and Minion attack (and health) calculations
(They are bizarre, really.) I thought that would be an issue, so I tested
it as well, and found no increased attack or HP, so that isn't an issue.

However, I will check out what's causing the issues. I didn't test the most
recent changes (but by god, I made sure that transformation worked), so
that might be causing some issues. I didn't have time to do that this
morning, so I'll check it out when I get home.

**Comment by webadict** [comment]
I found the issue... Of course it was gonna be bizarre, and I think only you can truly grasp how bizarre it is:

Apparently, I need to move those minions that don't exist but are being transformed (Ala Recomboulator or Faceless Manipulator with Brann Bronzebeard) to the Set Aside Zone, so that they exist so that when they're summoned, if they have any Spell Triggers, they can be removed when they're being re-transformed. This meant that it was completely random whether this bug occurred or not... Which it didn't when I tested it. I just got REALLY (un)lucky. Lesson learned. Don't not summon random minions just because they will never exist in the game in case they decide to muck up the place.

**Comment by webadict** [comment]
Although, you are right about the Jaraxxus interaction. I only tested Mal'Ganis -> Jaraxxus, but not Jaraxxus -> Mal'Ganis... Which again makes no sense, but whatever.

Regardless, this should be fixable.

**Comment by webadict** [comment]
There.

**Comment by webadict** [comment]
Finished Simulation Tests. No issues as of this post.

**Pull request merged**
