### PR TITLE
Update 1 for v1.0.3

### PR DESCRIPTION
**Pull request by webadict**
-Added all known Whispers of the Old Gods cards.
-Changed most card JSON integers to allow value providers
-Added Overload clarity text (Could be improved a bit better.)
-Added Player Attributes, which include Hand Count, Deck Count. Secret Count, Current Mana, and Max Mana
-Removed mana clamp in Sandbox Mode
-Fixed minor Charge mind control bug

### CODE REVIEW

**Comment by mayuso** [comment]
Is 1.1.0 planned to release with the new expansion? (I´m just curious, I am trying to learn as much as possible about different version control numbering systems).

**Comment by webadict** [comment]
Yeah, but I won't count it as the next expansion until all cards are added,
you know? This is more of a pre-update.

**Comment by mayuso** [comment]
Oh, I see, that makes sense. Thank you.

**Comment by webadict** [comment]
I also have no idea how C'Thun works, so this is what it is for now. I'm reading some varying accounts of how it works (Like Mistcaller, but what about re-adding to hand?)

It is 100% likely that the way I've implemented it is wrong.

**Comment by webadict** [comment]
It is now only 25% likely this is wrong. I don't think it is, but it's better programmed anyhow.

**Comment by demilich1** [comment]
Overall very nice PR, lots of very useful streamlining. Two small things regarding commit b2a731f

1. You made a change to the DrawCardEvent which may be problematic. Before the DrawCardEvent was fired always, even when the drawn card was discarded. You changed it to only fire when the card is actually added to the players hand. This may lead to bugs with cards such as Flame Leviathan, which (as far as I know) should also trigger when they are drawn, but the player's hand is full?

2. I don't know about C'thun, the way you implemented this means that he will get buffed even if he is not in your deck at the moment. On that note, I also think Mistcaller is not implemeted correctly, because he also will work for future minions (i.e. minions which were not in your deck while Mistcaller was played). I actually thought the BuffAnywhereSpell approach was more intuitive?

**Comment by webadict** [comment]
1. That's exactly what should happen. On draw effects do not trigger unless they get to your hand from your deck. Otherwise, it is simply a discard from deck effect (Which shouldn't proc discard effects either.) So, the Mine, Ambush, Flame Leviathan, and other such cards shouldn't activate if they get milled. [From the wiki](http://hearthstone.gamepedia.com/On-draw_effect): "On-draw effects are only activated through successful card draw. Overdrawing a card with an on-draw effect (attempting to draw it when the player already has a full hand) will not activate its on-draw effect."

2. Yes and no. The way Mistcaller is set up is actually 100% correct as of now, but the reason it's a no, is because it's technically due to a limitation of Hearthstone. I'm assuming once this is fixed, buffing inside the deck will be better (And the BuffAnywhereSpell would be correct.) That means playing Mistcaller and then the Golden Monkey should draw +1/+1 legendaries from the deck. Crazy, I know, but that is exactly how it should work. [From the wiki](http://hearthstone.gamepedia.com/The_Mistcaller): The Mistcaller's card text does not accurately describe the behaviour of its Battlecry. A more accurate description might be, "Give all minions in your hand 1+/1+, and whenever you draw a minion give it +1/+1". This behaviour is intended. However, the developers admit the way it is implemented is unideal, so it may be changed in the future. Most notably, at no point are cards in the player's deck granted enchantments.

Now, whether the update to C'Thun fixes this (It very well might!) is unknown until I can test it. It might also buff the card in the Graveyard, or wherever it is. I also need to create a Condition for the newest card Klaxxi, as it... It's just plain awful to try to figure out, so I don't plan to add it until after release or more information comes out.

**Comment by mayuso** [comment]
> It might also buff the card in the Graveyard, or wherever it is.

We can´t try the card yet, but according to the text, and information we have until now, I think it is save to assume it always buffs, no matter if it is in the graveyard, or even on the enemy deck. (If enemy uses Entomb, for example). 

I have a doubt with thoughtsteal (As is COPIES the card, so I guess it´s not technically YOUR C'thun).

**Comment by webadict** [comment]
Entomb won't for sure. Entomb causes a mind control before moving into the
deck (Might need to program that), so it will only ever work on Cthuns you
control. It shouldn't buff in the enemy deck based on what I've read, but
the release of Klaxxi means I don't know how it works just yet.

**Comment by demilich1** [comment]
There is also the open question regarding multiple C'Thuns. All the cards just state 'your C'Thun' but you may have more than 1 in the deck. I have a vague feeling that Blizzard just creates a new hidden counter called CTHUN_BUFF_COUNTER or something like that, which is just an attribute on the player. And all these interactions just increase the counter or (in the case of the Klaxxi) check it. That way all C'Thuns would have the same strength and it would also be much less complex to implement.

**Comment by webadict** [comment]
I think so too, but then I wonder if Klaxxi buffs itself if you don't have
C'Thun in your deck, which I don't quite know (maybe wherever it is is
super mysterious and counts card collection?)

**Comment by demilich1** [comment]
Hm, you are right, it would be really strange if Klaxxi would work without C'Thun in your deck. Waiting with the implementation of that one seems really reasonable :)

**Pull request merged**
