### PR TITLE
Event Trigger Conditions Update

### LINKED ISSUE #100: [Explosive Trap] + [Freezing Trap] interaction
Freezing Trap will still trigger even if an Explosive Trap is queued to trigger first and kill the attacking minion. The fatal damage is ignored and the minion is returned to the owner's hand. What should happen is that Freezing does not trigger at all when the minion is dead.

I looked into this, but was unable to find a quick fix. I think it is related to the trigger changes, where we now first collect all triggers which are supposed to fire, instead of firing triggers instantly. This is correct for almost all triggers, but I suppose secrets are a special case in that regard.

On that note, I discovered the following code in TriggerManager class:

```
// In order to stop premature expiration, check
			// for a oneTurnOnly tag and that it isn't delayed.
			if (event.getEventType() == GameEventType.TURN_END &&
					trigger instanceof SpellTrigger) {
				SpellTrigger spellTrigger = (SpellTrigger) trigger;
				if(spellTrigger.oneTurnOnly() && !spellTrigger.isDelayed() &&
						!spellTrigger.interestedIn(event.getEventType())) {
					spellTrigger.expire();
				}
				spellTrigger.delayTimeDown();
			}
```

@webadict Could you explain what this code is doing? I checked all cards and could not find any card which actually sets the turnDelay. I would really like to remove this piece of code if it is not used right now.

### PR DESCRIPTION
**Pull request by webadict**
-Fixed PlayerAttributeValueProvider for Frost Giant.
-Fixed Lightwell to properly target.
-Added new firing condition for event triggers and updated cards to use these new conditions.
EDIT: -Fixes #100 as well.

### CODE REVIEW

**Comment by kairos4242** [comment]
Are you going to be doing a PR with the new cards soon?

If not, I can.

**Comment by webadict** [comment]
I have every new card except Renounce Darkness, but I'm pushing all of these first, so that all those cards will work.

**Comment by webadict** [comment]
Well, I suppose I don't have Shifter Zerus just yet, but I bet I'll get him soon.

**Comment by webadict** [comment]
Really, it's mostly THIS change that I'm guessing demilich hates the most. Changing things with Triggers is never fun, especially because there's a lot that can go wrong, but I'm trying to push these changes as soon as I get one accepted, and some of them build off the last change, so it's a slow and steady progress. If demilich were online at the same time as me, it'd probably be a bit faster, but I'm fairly certain he lives on the other side of the planet. I'm guessing this will take a week? Maybe more? But if you want, you can check out the test build in my fork with almost every current card.

**Comment by webadict** [comment]
https://github.com/webadict/metastone/tree/test will probably be the most up to date, but most likely to have bugs branch.

**Comment by kairos4242** [comment]
Alright, I was looking off of your master branch, so I only saw some of them. The PRs taking a while to do individually is annoying, but it's not like we're in some sort of time crunch, so I don't find it that big a deal. 

Also, why not Renounce Darkness? Golden Monkey worked just fine, and the way they work is similar in my mind at least. Is it just that you haven't got around to it?

**Comment by webadict** [comment]
The issue is the cost reduction. Hearthstone is a weird, weird game when it comes to modifying cards in your deck. You don't ACTUALLY modify those particular ones. So, giving each of those cards a cost modifier is bizarre.

However, you might be right. I might make the card tomorrow. We'll see.

**Comment by kairos4242** [comment]
I remember reading something related to that actually on r/hearthstone, something about when a minion is pulled by Deathlord, it doesn't gain the bonus stats from Mistcaller. Hearthstone treats minions in your deck and hand very unusually.

I'll take a crack at it tomorrow too, if whatever you try doesn't get it. It may also help to wait until the expansion is released, then do some testing to see how it works.

**Comment by webadict** [comment]
Well, holy crap. I finally got a working copy. It's a LOT harder than it looks.

On the plus side, I needed to do part of it anyway for the new card.

**Pull request merged**
