### PR TITLE
Added two more sites that you can import decks from.

### PR DESCRIPTION
**Pull request by ikhaliq15**
User can now import decks from Icy-Veins.com and Heartheed.com

### CODE REVIEW

**Comment by ikhaliq15** [comment]
Hey, just want to let you know that this is my first time contributing to any open source project. I know my changes aren't that big of a deal but I just wanted to try contributing to something. If you like the changes, please add it to master.

**Comment by demilich1** [comment]
Hi! First of all, thanks a lot for your contribution.

However, when cloning your repo and trying to run MetaStone, I get some compile errors. It seems that everything in the org.jsoup package cannot be resolved. You probably need to enter this .jar in the respective .gradle files.

Please note: If the library you are using is available in an online repository, it would be preferable if you just link it in the .gradle instead of checking in the binaries. You can look at the inclusion of the org.apache.commons package for an example.

**Comment by ikhaliq15** [comment]
Okay, I'll work on it.

**Comment by ikhaliq15** [comment]
Okay, I fixed it. It should work now. Do I need to create a new pull request?

**Comment by demilich1** [comment]
No, you don't need to create a new pull request, this one will update automatically ;)

Everything seems to work fine now, I have just another tiny change request. The Hearthhead importer class is spelled 'HearthHeedImporter.java' . This might seem pedantic, but would you mind fixing the spelling? After that I will merge it in.

Thanks again for your contribution!

**Comment by ikhaliq15** [comment]
Fixed.

**Pull request merged**
