### PR TITLE
Updated README.

### PR DESCRIPTION
**Pull request by mayuso**
"How to run it" for Linux users.

### CODE REVIEW

**Comment by demilich1** [comment]
I never actually tried running it under Linux, so thanks for the guide. Got a question though: Does this really require the 'sudo'?

**Comment by mayuso** [comment]
It is not a must. Seems to work fine for me without `sudo` (Just tested it), but still I would recommend using it. Using `sudo` might prevent crashes caused by unreachable external libraries because of file privileges.

**Comment by demilich1** [comment]
Would you mind removing the 'sudo' command or at least mention that it should work fine without it? My impression is that people who are using Linux are usually pretty sensible regarding all things security and requiring a 'sudo' may seem fishy to some. I just fear that it may lead to some people avoid trying it out.

**Comment by mayuso** [comment]
You can delete this PR.

**Pull request closed without merging**
