### PR TITLE
One Night in Karazhan Update

### LINKED ISSUE #197: Corrupted Seer only targets enemy minions
As the title says, Corrupted Seer only targets enemy minions, which is not how it behaves in game or what its text says, as he is meant to damage "all non-Murloc minions".

It also has an incorrect rarity as it is a rare card in Hearthstone and a common one here.

Addendum : I also noticed the scarabs summoned by Obsidian Destroyer are murlocs, while they are beasts in hearthstone.

EDIT : Also, Rend Blackhand is incorrectly labelled as a Dragon (which he is not).

### PR DESCRIPTION
**Pull request by webadict**
- Added Karazhan cards, card set, and the ability to use most of them.
- Updated a few spells to work with the new cards.
- Added NEUTRAL and SELF hero classes. Currently, NEUTRAL does nothing, but moving all NEUTRAL cards to use the correct hero class would be preferred.
- Fixed some other cards like Rend Blackhand, Corrupted Seer, etc. (Fixes #197)

### CODE REVIEW

**Comment by demilich1** [comment]
Just did a quick /gradlew test run, getting a lot of exceptions, so I will hold on with the merge for now

**Comment by webadict** [comment]
You did? I didn't get any. I'll try to see what's up, but it doesn't appear to have any issues on my end.

**Comment by demilich1** [comment]
Does this PR maybe depend on the other (with the DiscardCard changes) ?

**Comment by webadict** [comment]
No, the DiscardCardSpell is a functional change unrelated to this, so I pushed it separately. I don't believe there's anything else, which is why I'm kinda confused.

**Comment by demilich1** [comment]
Let me double check, maybe I did something wrong while switching branches

**Comment by demilich1** [comment]
Found the issue: Everything works inside the actual simulator, however the unit tests are failing. This is because the class MassTest.java has a custom getRandomHeroClass() method which does not account for the new classes NEUTRAL and SELF.

There is one little strange thing though: When performing a simulation in MetaStone with 'Play Random' behaviour, I sometimes get the warning message inside the console:
``Player 'Garrosh Hellscream' (Garrosh Hellscream) tries to perform an action, but it is not his turn!``

**Comment by webadict** [comment]
I think--and this is just a guess--that is because of Yogg-Saron's battlecry combining with Sylvanas' deathrattle (Or anything else that steals during a Battlecry Phase), technically, this is purposeful, but I kinda set it up in a way that I thought would work best.

I can fix the class issues.

For some reason, my tests don't appear to be running. No idea why. It tells me everything's going, but nothing pops up. Great!

**Comment by webadict** [comment]
Oh sweet, I was doing the tests wrong! Got it!

**Comment by webadict** [comment]
Alright, fixed the random class test. Should work whenever a new class is added too!

**Comment by webadict** [comment]
The Yogg-Saron issue is a bit of a sticky situation. Right now, it's basically coded to finish the Battlecry with two distinctly insane players. There's probably a better way to do it, but the way it does so now is because I wanted to avoid any possible issues that aren't covered. I'm sure there's a much better way to do it, though.

**Comment by demilich1** [comment]
Thanks for fixing the tests! Regarding the Yogg issue: this is actually tricky. Basically this boils down to Battlecries being GameActions, which is debatable. For me the definition is like this: a GameAction is everything which requires user interaction. Now for MetaStone, Battlecries do require user interaction, i.e. selecting a target. In the real Hearthstone game though, you select a target WHILE playing the card, there is no separate step. The Battlecry being a separate action also causes other problems, i.e. the infamous crash bug in Sandbox mode, when you press the 'Back to main menu' button while prompted to select a Battlecry. In my opinion the best solution would be to do it like Hearthstone, requiring the Battlecry target selection while playing the Battlecry card. However, this is a large change and for now I think we can live with the warning (as it won't cause any trouble).

**Pull request merged**
