### PR TITLE
Card Updates

### PR DESCRIPTION
**Pull request by webadict**
Fixes:
-Added remaining LoE cards.
-Fixed Tracking
-Added correct Discover mechanic

Current Identified Issues:
-Rumbling Elemental does not apply AFTER the minion is summoned.
-Reno Jackson does not use a HashSet just yet. (Not really an issue, but I figure it's probably a little bit faster.)
-Mistress of Pain does not correctly heal when ARMOR_SUIT and TAKE_DOUBLE_DAMAGE are active.
-Sir Finley Mrrgglton does not stop from receiving currently owned Hero Power. However, does he stop from receiving only your original one, or also any copied ones as well?

Unknown Value Conditions:
-Are Murlocs resurrected from your opponent with Anyfin Can Happen?

### CODE REVIEW

**Comment by Chibi1234** [comment]
yay more cards!

**Comment by webadict** [comment]
... I don't think there's an easy way to grab the actual costs of the spell played. Geez, man... Geez. I had to do some hoop jumping for Djinni, but... I dunno if I can get the same results for Summoning Stone. At least, not nearly as easily.

**Comment by webadict** [comment]
... Hmm... Maybe I should just cheat...

**Comment by Chibi1234** [comment]
Instead of trying to grab the cost of a spell you maybe could do a really long... complex... giant... thing...

You could make it so if you play a 1 mana spell  random 1 mana minion is summoned and you do it seperately for each mana value but that would be rly boring to make ._.

**Comment by webadict** [comment]
Technically, you're not wrong. That would be the long way around it, and it's not a bad idea. The problem that pops up while doing that is that when the spell card is played, it tries to play the spell, but the card would need multiple triggers in order to do something like that, and that's probably a bad way to do that.

On the plus side, there is a relatively simple way to make it work, but I was just a little bit tired after messing around for so long on Djinni (who works fantastically now!), and it uses a similar method that Djinni does. Since the card is casted by the point that the trigger activates, the card should exist in the Game Environment as PENDING_CARD. I'm taking a wild guess right now, but I'm assuming that all card attributes and modifiers should still exist in it, so any Mana cost changes should be able to be found, since that was my issue with what I was doing yesterday (I was grabbing the wrong mana cost method.)

So, I'll get something done in... I dunno, 10 hours? I've got some things to do before then.

**Comment by Chibi1234** [comment]
Alright! GL!

**Comment by webadict** [comment]
Discover mechanic is now correctly using 300% increased chance of class cards, as well as using the correct class.

**Comment by demilich1** [comment]
Thanks a lot implementing all those League of Explorers cards. Much appreciated.

I just checked out your version and there are still some exceptions being thrown. The first ones I noticed are originating from CopyDeathrattlesSpell and PlayRandomBehaviour (I suppose there are some troubles with the new Discover mechanic), but there are more. I would prefer to delay the merge of the PR until those are fixed. If you want, I can assist you in fixing the exceptions, but that would require that you always push your local commits to github, so we don't do a lot of conflicting local work.

When I am done with some major additions/changes to the codebase, I always run SimulationMode -> Select Behaviour 'PlayRandom' -> set games to 100000 and run. I do this for each class, Warrior vs Warrior 100000 games, Priest vs Priest 100000 games, etc. The idea is to let the AI play every card in the game in many many different situations to find possible bugs. Just a little tip to help you testing. Usually, when all classes complete all 100000 games, the code is pretty stable.

**Comment by webadict** [comment]
Done.

Issue was that Deathrattle cards never existed as Deathrattle cards. There was nothing to show they even had a Deathrattle until the Card was turned into an Actor.

Also, I forgot to account for null Deathrattles in CopyDeathrattleSpell. Also, Unearthed Raptor shouldn't even be able to target non-Deathrattle minions, since the card doesn't (Which is odd, since it isn't written on there like that.)

I also fixed some other issues while I was doing that. Cards were missing the Battlecry Attribute, and Shadowpan had one while I was checking stuff.

The only issue I found was a really obscure one that I can't reproduce. Defender of Argus crashed the game, but I have no idea how.

08:51:41 ERROR - ERROR while playing card [MINION 'Defender of Argus' Manacost:4] reference: [CardReference playerId:0 cardName:Defender of Argus cardLocation:HAND cardId:15]

It only happened on Paladin v. Paladin, and I didn't grab the Error Log, because I thought it was something that I added, but nothing else I did really did ANYTHING to Defender of Argus. I'm even pretty sure I didn't add the Battlecry tag.

**Comment by demilich1** [comment]
For me, the main suspect is Brann Bronzebeard. It caused multiple issues for me after the last merge. There may still be remaining issues in the code with double battlecries.

Anyway, I will test your version again tomorrow and merge it if no major issues arise. Thanks again!

**Comment by webadict** [comment]
It's possible, I suppose, but the way you had implemented it before made the second Battlecry targetable. I'll see if I can figure it out.

**Comment by webadict** [comment]
I made a Brann deck and added a bunch of Battlecry minions. I didn't see any issues with them pop up when I ran the 100k sim. It could've been an issue with one of the minions. I totally misspelled attributes, so it might've cause some issues.

As for the second change I made, I have decided to reformat many of the cards. This is just a first run through, getting most of the cards in order. I made a program that sorta refactors the cards to be much nicer and tidier, but I haven't added all the keywords in the right order yet, so some of the big ones (well, mainly little big ones) like onEquip and onUnequip will be smashed into the bottom until I work on it some more, but the few other ones I've got going pretty well.

If you've got any suggestions on keyword order (It's fairly logical right now, but something like baseManaCost could be lower, if that's better, or race could be higher, who knows?)

The only card changes I made were to cards I screwed up in the first place, so attribute should be changed back to attributes.

**Pull request merged**
