### PR TITLE
Build config

### PR DESCRIPTION
**Pull request by akoscz**
- renamed `AppConfig.java` to `BuildConfig.java` since its how shared across both `app` and `game` modules
- adding usage of gradle [BuildConfigPlugin](https://github.com/mfuerstenau/gradle-buildconfig-plugin) to generate `BuildConfig.java` at build time.
- `project.version` is now set only in one place, that is the root module `metastone/build.gradle` file and it propagated down to all sub modules.
- the project name is set to `metastone` in `settings.gradle` and is referenced by `rootProject.name` since `project.name` is a read only property.  By us setting the `rootProject.name` property this ensures that the project name remains `metastone` in case if someone clones the repo into a folder with some other name.
- all other BuildConfig attributes are declared in `shared/build.gradle` buildConfig block
- USER_HOME_METASTONE is now defined in the `shared/build.gradle` file.  On Windows this location will point to `C:\Users\[username]\Documents\metastone` and all other non-windows OS's to `/Users/[username]/metastone`.  These paths are determined by the `javax.swing.filechooser.FileSystemView` component's `getDefaultDirectory()` which does the right thing across all platforms.
- added a convenience build property to launch the app into developer mode from the command line.  You can now specify the `-PDEV_BUILD` property when running the app through gradle.  This will set the `BuildConfig.DEV_BUILD` property to `true`.
    - Windows `gradlew.bat run -PDEV_BUILD`
    - Linux / OSX `./gradlew run -PDEV_BUILD`
- updated README.md to point out that when building through an IDE (in particular Eclipse) it is necessary to first generate the BuildConfig.java file by running  the `compileBuildConfig` gradle task from the command line.

### CODE REVIEW

**Comment by demilich1** [comment]
I just tested this branch and the command
`gradlew build` no longer works. This is the command I use when bundling a release, now there is an error message:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:startScripts'.
> No value has been specified for property 'mainClassName'.
```

**Comment by akoscz** [comment]
Ah, my mistake.  I removed `mainClassName` from build.gradle because i did not find any references to it.  Thanks for catching this.  I will add it back.

**Comment by akoscz** [comment]
@demilich1 give it a try now.  I had to add an `appName` to the javafx closure because on the `build` task was using the module name `app` as the application binary name.   Now it will use the `rootProject.name` property defined in `settings.gradle`

**Comment by akoscz** [comment]
btw,  looks like the author of the JavaFX gradle plugin that we are using is no longer maintaining the project. https://bitbucket.org/shemnon/javafx-gradle/issues/49/documentation-and-a-working-sample#comment-26159475

In a future change, I'd like to update to a JavaFX plugin that is currently being maintained such as: https://github.com/FibreFoX/javafx-gradle-plugin

**Comment by demilich1** [comment]
Works fine now, thanks. I was aware that the plugin is no longer maintained, but didn't know that there is one which is actively developed.

**Comment by akoscz** [comment]
Regarding the usage of `USER_HOME_METASTONE` in BuildConfig.java,  is this what you had in mind about the location of the `metastone/cards` dir on Windows and on non-Windows systems?

**Comment by demilich1** [comment]
Yes, this is exactly what I had in mind, very nice :)

**Comment by akoscz** [comment]
Sweet!  Thanks!

**Pull request merged**
